USE [master]
GO

/****** Object:  Database [TestChekDB]    Script Date: 10/15/2018 7:24:16 PM ******/
CREATE DATABASE [TestChekDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestChekDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TestChekDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestChekDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TestChekDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TestChekDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestChekDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestChekDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestChekDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestChekDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestChekDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestChekDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestChekDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestChekDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestChekDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestChekDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestChekDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestChekDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestChekDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestChekDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestChekDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestChekDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestChekDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestChekDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestChekDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestChekDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestChekDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestChekDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestChekDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestChekDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TestChekDB] SET  MULTI_USER 
GO

ALTER DATABASE [TestChekDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestChekDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestChekDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestChekDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestChekDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestChekDB] SET QUERY_STORE = OFF
GO

USE [TestChekDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TestChekDB] SET  READ_WRITE 
GO


